# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_trip_current_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='current_trip',
            field=models.BooleanField(default='False'),
        ),
    ]
