# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0003_auto_20161110_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='current_trip',
        ),
    ]
