# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 16:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_trip_current_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='school_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
