# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-10 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0007_auto_20161110_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_raiser_type',
            name='super_group',
            field=models.CharField(default='Aramark', max_length=75),
        ),
        migrations.AlterField(
            model_name='fund_raiser_type',
            name='description',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_trip',
            field=models.BooleanField(default='False', verbose_name='current Trip?'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='insurance_cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='insurance Cost'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_company_contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_company_email',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='contact Email'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_company_phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='contact Phone'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_coordinator',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='coordinator'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_coordinator_email',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='coordinator Email'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_cost',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='trip Cost'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='end Date'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='trip_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='start Date'),
        ),
    ]
