# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 03:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0008_auto_20161110_1702'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund_raiser',
            options={'verbose_name': 'Fund Raiser', 'verbose_name_plural': 'Fund Raisers'},
        ),
        migrations.AlterModelOptions(
            name='fund_raiser_type',
            options={'verbose_name': 'Fund Raiser Type', 'verbose_name_plural': 'Fund Raiser Types'},
        ),
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AlterModelOptions(
            name='trip_commitment',
            options={'verbose_name': 'Trip Commitment', 'verbose_name_plural': 'Trip Commitments'},
        ),
        migrations.AlterField(
            model_name='fund_raiser',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='fund_raiser',
            name='profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='fund_raiser_type',
            name='super_group',
            field=models.CharField(default='Aramark', max_length=75, verbose_name='super Group'),
        ),
        migrations.AlterField(
            model_name='trip_commitment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='trip.Trip'),
        ),
    ]
