# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0010_fund_raiser_fund_raiser_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fund_raiser_type',
            options={'ordering': ('description',), 'verbose_name': 'Fund Raiser Type', 'verbose_name_plural': 'Fund Raiser Types'},
        ),
        migrations.AlterField(
            model_name='fund_raiser',
            name='description',
            field=models.CharField(max_length=200, verbose_name='fund Raiser'),
        ),
        migrations.AlterField(
            model_name='fund_raiser',
            name='fund_raiser_date',
            field=models.DateField(verbose_name='fund Raiser Date'),
        ),
        migrations.AlterField(
            model_name='fund_raiser',
            name='fund_raiser_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trip.Fund_Raiser_Type', verbose_name='fund Raiser Type'),
        ),
        migrations.AlterField(
            model_name='fund_raiser',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='profit'),
        ),
        migrations.AlterField(
            model_name='fund_raiser',
            name='profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='profit Percentage'),
        ),
        migrations.AlterField(
            model_name='trip_commitment',
            name='email',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AlterField(
            model_name='trip_commitment',
            name='period',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='trip_commitment',
            name='phone_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='trip_commitment',
            name='phone_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
