# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 06:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0012_auto_20161111_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip_commitment',
            name='student_grade',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)]),
        ),
    ]
