# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 03:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0013_auto_20161111_0143'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Payment_Date',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(verbose_name='payment_Date')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='payment_Amount')),
                ('final_payment', models.NullBooleanField(default=0)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_payment_dates', to='trip.Trip')),
            ],
            options={
                'verbose_name_plural': 'Trip Payment Dates',
                'verbose_name': 'Trip Payment Date',
            },
        ),
        migrations.AlterField(
            model_name='trip_commitment',
            name='going_on_trip',
            field=models.CharField(choices=[('U', 'Unknown'), ('Y', 'Yes'), ('N', 'No')], default='U', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='trip_payment_date',
            unique_together=set([('trip', 'payment_date')]),
        ),
    ]
