# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-14 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0015_auto_20161113_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund_Raiser_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=50, verbose_name='Fund Raiser Item')),
                ('display_order', models.IntegerField(verbose_name='Display Order')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='payment_Amount')),
                ('profit', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='payment_Amount')),
                ('profit_percentage', models.IntegerField(verbose_name='Profit Percentage')),
                ('fund_raiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_raiser_items', to='trip.Fund_Raiser')),
            ],
            options={
                'verbose_name_plural': 'Fund_Raiser_Items',
                'verbose_name': 'Fund_Raiser_Item',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField(verbose_name='payment_Date')),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='payment_Amount')),
                ('check_number', models.CharField(blank=True, max_length=20, null=True)),
                ('deposit_date', models.DateField(blank=True, null=True, verbose_name='deposit_Date')),
                ('trip_commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_payments', to='trip.Trip_Commitment')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Fund_Rasier',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_sold', models.IntegerField(verbose_name='quantity_Sold')),
                ('fund_raiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_raiser_items', to='trip.Fund_Raiser_Item')),
                ('trip_commitment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_fund_raiser', to='trip.Trip_Commitment')),
            ],
        ),
    ]
