# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0016_fund_raiser_item_payment_student_fund_rasier'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student_Fund_Rasier',
            new_name='Student_Fund_Raiser',
        ),
        migrations.AlterField(
            model_name='trip_payment_date',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='payment Amount'),
        ),
        migrations.AlterField(
            model_name='trip_payment_date',
            name='payment_date',
            field=models.DateField(verbose_name='payment Date'),
        ),
    ]
