# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 04:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0018_fund_raiser_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='fund_raiser_profit',
            name='fund_raiser',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='fund_raiser_fund', to='trip.Fund_Raiser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fund_raiser_profit',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_raiser_trip', to='trip.Trip_Commitment'),
        ),
    ]
