# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 04:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0019_auto_20161114_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fund_raiser_profit',
            old_name='trip',
            new_name='trip_commitment',
        ),
    ]
