# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0020_auto_20161114_2352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Commitment_Dashboard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=510)),
                ('student_grade', models.IntegerField()),
                ('period', models.CharField(max_length=2)),
                ('going_on_trip', models.CharField(choices=[('U', 'Unknown'), ('Y', 'Yes'), ('N', 'No')], default='U', max_length=1)),
                ('purchase_insurance', models.BooleanField(default=0)),
                ('email', models.CharField(blank=True, max_length=75, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True)),
                ('trip_description', models.CharField(max_length=200)),
                ('trip_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('insurance_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_trip', models.BooleanField(default=0)),
                ('total_payment', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_fund_raiser_profit', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_amount_due', models.DecimalField(decimal_places=2, max_digits=6)),
                ('current_payment_date', models.DateField()),
                ('current_payment_due', models.DecimalField(decimal_places=2, max_digits=6)),
                ('trip_balance', models.DecimalField(decimal_places=2, max_digits=6)),
                ('account_up_to_date', models.CharField(max_length=3)),
            ],
            options={
                'db_table': 'trip_trip_commitment_dashboard_vw',
                'verbose_name': 'Trip Commitment Dashboard',
                'managed': False,
                'verbose_name_plural': 'Trip Commitments Dashboard',
            },
        ),
        migrations.CreateModel(
            name='Trip_current_payment_due',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('current_trip', models.BooleanField(default=0)),
                ('current_payment_date', models.DateField()),
                ('current_amount_due', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'db_table': 'trip_trip_current_payment_due',
                'verbose_name': 'Trip Current Payment Due',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(blank=True, max_length=75, null=True)),
                ('phone_1', models.CharField(blank=True, max_length=15, null=True)),
                ('phone_2', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.AlterField(
            model_name='payment',
            name='check_number',
            field=models.CharField(default=111, max_length=20, verbose_name='check Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='deposit_date',
            field=models.DateField(blank=True, null=True, verbose_name='deposit Date'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='payment Amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='payment Date'),
        ),
    ]
