# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0021_auto_20161128_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='svid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
