# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-28 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0023_auto_20161128_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip_commitment',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='trip.Student'),
            preserve_default=False,
        ),
    ]
