# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0025_auto_20161128_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Fund_Raiser_Detail',
            fields=[
                ('fund_raiser_profit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('profit', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='profit')),
                ('date_entered', models.DateField()),
                ('fund_raiser_description', models.CharField(max_length=200)),
                ('profit_percentage', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='profit')),
            ],
            options={
                'db_table': 'trip_fund_raiser_detail_vw',
                'verbose_name': 'Trip Fund Raiser Detail',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Trip_Fund_Raiser_Profit',
            fields=[
                ('trip_commitment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fund_raiser_type', models.CharField(max_length=10)),
                ('fund_raiser_id', models.IntegerField()),
                ('fund_raiser_description', models.CharField(max_length=200, verbose_name='Fund Raiser')),
                ('total_profit', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Total Profit')),
            ],
            options={
                'db_table': 'trip_all_fund_raiser_profit_vw',
                'verbose_name': 'Trip Fund Raiser Profits',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='student',
            name='svid',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='SV ID'),
        ),
        migrations.AlterField(
            model_name='trip_commitment',
            name='student_grade',
            field=models.IntegerField(choices=[(8, 8), (9, 9), (10, 10), (11, 11), (12, 12)], verbose_name='Grade'),
        ),
    ]
