# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0026_auto_20161211_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fund_raiser_item',
            name='profit_percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Profit Percentage'),
        ),
    ]
