# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-07 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0027_auto_20161211_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip_Fund_Raiser_Item_Detail',
            fields=[
                ('trip_commitment_id', models.IntegerField()),
                ('fund_raiser_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_fund_raiser_id', models.IntegerField()),
                ('fund_raiser_id', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('item_description', models.CharField(max_length=50)),
                ('display_order', models.IntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='cost')),
                ('sub_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='profit')),
                ('profit', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='profit')),
                ('profit_percentage', models.IntegerField()),
                ('profit_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='profit')),
                ('profit_percentage_total', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='profit')),
                ('fund_raiser', models.CharField(max_length=200)),
                ('quantity_sold', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Trip Fund Raiser Item Detail',
                'db_table': 'trip_fund_raiser_item_detail_vw',
                'managed': False,
            },
        ),
    ]
